### ISSUE TITLE
pip install pyreadline

### ISSUE THREAD

**Issue by jihu9** [picasso250/wechat-cli#1]
RT 使用了pyreadline库，需要安装 建议在readme 增加说明

**Comment by picasso250** [comment]
我在使用cygwin的时候，并不需要安装pyreadline库（默认自带）
你使用的是什么系统环境？

**Comment by picasso250** [comment]
确认，在mac上也不需要（通过brew安装的python3）

**Comment by picasso250** [comment]
看起来，需要部署一下CI，让在几个环境下都测试一下

**Comment by picasso250** [comment]
在Windows cmd下需要这个pyreadline，已经在readme里面加了。谢谢。
