### ISSUE TITLE
不能扫描二维码

### ISSUE THREAD

**Issue by EncodingDavid** [picasso250/wechat-cli#4]
使用微信扫描以及手机自带的扫描，依旧扫描不到

**Comment by picasso250** [comment]
截图我看一下

**Comment by RoyZhang7** [comment]
遇到了一样的问题。
![image](https://user-images.githubusercontent.com/17587438/68959075-5ffd9100-079b-11ea-9f18-4c4f7a49fca7.png)
应该是print格式。我可能会提交个pr。

**Comment by picasso250** [comment]
应该是这个值不对引起的

    enableCmdQR = 2 # 1 也试一下

关于这个值是1还是2，我也没有什么好的判断办法。

我现在的判断方法是windows给1，其他给2，可是如果你的windows的powershell的字体修改了的话，也是会有问题的。

**Comment by luckoct** [comment]
扫到了但是点登陆没反应

**Comment by picasso250** [comment]
现在会让用户自己决定enableCmdQR 的值。

**Comment by luckoct** [comment]
> 现在会让用户自己决定enableCmdQR 的值。

现在微信扫描不能登录哦

**Comment by picasso250** [comment]
我自己用wsl是可以登陆的。你有没有把1和2都试全呢？
